import type { Setting } from "../../types"

// ── SEED DATASET — ClubSport Wheel Base V2.5 on-wheel tuning menu ─────
// DRAFT values authored by Kai (hybrid sourcing). Nathan to verify each
// against the actual on-wheel tuning menu before this is treated as truth.
// Every setting is flagged `unverified: true` until confirmed.
//
// The V2.5 is a belt-driven base (~8Nm peak). Because it has less raw torque
// than a DD, you'll typically run FF higher (80–100) to achieve comparable
// wheel weight. Xbox platform only — no PC Control Panel on Xbox.

export const fanatecV25Settings: Setting[] = [
  {
    id: "fanatec-v25-sen",
    name: "Sensitivity",
    abbreviation: "SEN",
    category: "wheel-base",
    subcategory: "rotation",
    hardware: ["fanatec-v25"],
    platform: ["xbox"],
    location: { access: "on-wheel-tuning", path: "Tuning menu → SEN" },
    description:
      "Total steering rotation (lock-to-lock). Set to AUTO so the game decides the correct rotation per car. On console titles like Forza and F1, AUTO is strongly recommended — these games send a rotation signal and the wheel obeys it.",
    valueType: { kind: "auto-or-numeric", min: 90, max: 1080, default: "AUTO", unit: "°" },
    increaseEffect: "More degrees of rotation — slower, more realistic steering arc, less nervous on straights.",
    decreaseEffect: "Fewer degrees — faster steering input needed, can feel twitchy.",
    sweetSpot: "Leave on AUTO. Only override if the game ignores the rotation signal; then match the real car's lock-to-lock.",
    warnings: [
      "Setting SEN manually while the game also sets rotation can double-scale your steering, making it far too sensitive.",
    ],
    unverified: true,
  },
  {
    id: "fanatec-v25-ff",
    name: "Force Feedback Strength",
    abbreviation: "FF",
    category: "wheel-base",
    subcategory: "force-feedback",
    hardware: ["fanatec-v25"],
    platform: ["xbox"],
    location: { access: "on-wheel-tuning", path: "Tuning menu → FF" },
    description:
      "Overall force feedback strength — the master volume for all wheel forces. Because the V2.5 is belt-driven (~8Nm) rather than direct-drive, you generally need to run this higher than a DD to achieve a satisfying wheel weight.",
    valueType: { kind: "numeric", min: 0, max: 100, default: 100, unit: "%" },
    increaseEffect: "Heavier, stronger wheel forces — more physical feedback, but more forearm fatigue on long stints.",
    decreaseEffect: "Lighter wheel — easier to hold for extended play but forces lose their punch.",
    sweetSpot:
      "80–100 is a common starting range on the V2.5. Because the belt motor peaks lower than a DD, clipping is less aggressive — you can often run it higher without flattening detail.",
    warnings: [
      "Values above ~95 can still clip on the strongest forces (e.g., hitting a kerb hard), washing out fine texture.",
      "Pair with in-game FFB Scale to avoid double-boosting — one of the two should be the primary control.",
    ],
    interactsWith: [
      { settingId: "fanatec-v25-fei", relationship: "FF sets the volume; FEI sets the sharpness of what you hear at that volume." },
    ],
    unverified: true,
  },
  {
    id: "fanatec-v25-fei",
    name: "Force Effect Intensity",
    abbreviation: "FEI",
    category: "wheel-base",
    subcategory: "force-feedback",
    hardware: ["fanatec-v25"],
    platform: ["xbox"],
    location: { access: "on-wheel-tuning", path: "Tuning menu → FEI" },
    description:
      "Controls the sharpness and crispness of individual FFB effects (bumps, kerbs, surface texture). Lower values smooth and round off the signal; higher values keep effects crisp and immediate.",
    valueType: { kind: "numeric", min: 0, max: 100, default: 100, unit: "%" },
    increaseEffect: "Sharper, more defined effects — every kerb and surface change is crisp and distinct.",
    decreaseEffect: "Softer, smoother effects — gentler on the wrists and less harsh, but fine detail is blended away.",
    sweetSpot: "80–100 is a reasonable starting point. On the belt base the signal is slightly softer than a DD, so keeping FEI high helps preserve crispness.",
    unverified: true,
  },
  {
    id: "fanatec-v25-sho",
    name: "Shock / Vibration Intensity",
    abbreviation: "SHO",
    category: "wheel-base",
    subcategory: "force-feedback",
    hardware: ["fanatec-v25"],
    platform: ["xbox"],
    location: { access: "on-wheel-tuning", path: "Tuning menu → SHO" },
    description:
      "Intensity of the rumble/shock effects generated by the base itself (distinct from pedal vibration). These simulate road texture, impacts, and ABS pulses through the wheel.",
    valueType: { kind: "numeric", min: 0, max: 100, default: 100, unit: "%" },
    increaseEffect: "Stronger rumble and shock through the wheel — more tactile feel for surface changes and impacts.",
    decreaseEffect: "Smoother, less buzzy wheel — reduces noise from road texture being fed back as vibration.",
    sweetSpot: "50–80 is a reasonable starting range. High values can feel harsh on rough surfaces; tune to taste.",
    unverified: true,
  },
  {
    id: "fanatec-v25-dri",
    name: "Drift Mode",
    abbreviation: "DRI",
    category: "wheel-base",
    subcategory: "force-feedback",
    hardware: ["fanatec-v25"],
    platform: ["xbox"],
    location: { access: "on-wheel-tuning", path: "Tuning menu → DRI" },
    description:
      "Adjusts the self-centering behaviour to assist or hinder drift-style driving. OFF = normal centering. Positive values add spring-back force; negative values reduce or reverse the centering, letting the wheel travel more freely during oversteer.",
    valueType: { kind: "enum", options: ["OFF", "-5", "-4", "-3", "-2", "-1", "0", "1", "2", "3", "4", "5"], default: "OFF" },
    increaseEffect: "More aggressive self-centering — wheel snaps back to centre, suits grip/circuit driving.",
    decreaseEffect: "Weaker centering — wheel sits more neutrally during slides, suits drift/rally driving.",
    sweetSpot: "OFF or 0 for most racing. Negative values for dedicated drift/rally sessions.",
    unverified: true,
  },
  {
    id: "fanatec-v25-for",
    name: "Force",
    abbreviation: "FOR",
    category: "wheel-base",
    subcategory: "force-feedback",
    hardware: ["fanatec-v25"],
    platform: ["xbox"],
    location: { access: "on-wheel-tuning", path: "Tuning menu → FOR" },
    description:
      "Scales the constant/steady-state force component of the FFB signal. This is different from FF — FOR specifically affects the sustained tyre-load forces rather than the overall amplitude.",
    valueType: { kind: "numeric", min: 0, max: 100, default: 100, unit: "%" },
    increaseEffect: "Stronger sustained cornering load — wheel pulls harder when the car is generating lateral G.",
    decreaseEffect: "Lighter sustained load — less arm effort in corners, but you lose the weighted feeling of grip.",
    sweetSpot: "100 is the default; lower if steady-state forces feel too fatiguing relative to transient effects.",
    unverified: true,
  },
  {
    id: "fanatec-v25-spr",
    name: "Spring",
    abbreviation: "SPR",
    category: "wheel-base",
    subcategory: "force-feedback",
    hardware: ["fanatec-v25"],
    platform: ["xbox"],
    location: { access: "on-wheel-tuning", path: "Tuning menu → SPR" },
    description:
      "Spring force that centres the wheel. This mainly affects desktop mode and games that use DirectInput spring effects rather than proper FFB telemetry. Most modern titles ignore it.",
    valueType: { kind: "numeric", min: 0, max: 100, default: 100, unit: "%" },
    increaseEffect: "Stronger return-to-centre spring — can feel artificial in games that use it.",
    decreaseEffect: "Weaker spring — less artificial centering pull.",
    sweetSpot: "100 for compatibility; most modern racing titles send their own centering forces via FFB and ignore this.",
    warnings: ["Some older or arcade titles use DirectInput spring — if the wheel feels overly springy in a specific game, reduce SPR."],
    unverified: true,
  },
  {
    id: "fanatec-v25-dpr",
    name: "Damper",
    abbreviation: "DPR",
    category: "wheel-base",
    subcategory: "force-feedback",
    hardware: ["fanatec-v25"],
    platform: ["xbox"],
    location: { access: "on-wheel-tuning", path: "Tuning menu → DPR" },
    description:
      "Resistance damper for desktop/legacy DirectInput mode. Similar to SPR, most modern sim-racing titles override this with their own damper via FFB — but it can add drag in games that don't.",
    valueType: { kind: "numeric", min: 0, max: 100, default: 100, unit: "%" },
    increaseEffect: "Heavier, more resistant wheel movement — adds inertia.",
    decreaseEffect: "Freer wheel — less drag, more reactive.",
    sweetSpot:
      "100 for compatibility. If the wheel feels sluggish in a specific title, experiment with lower values.",
    unverified: true,
  },
  {
    id: "fanatec-v25-abs",
    name: "ABS Vibration",
    abbreviation: "ABS",
    category: "wheel-base",
    subcategory: "force-feedback",
    hardware: ["fanatec-v25"],
    platform: ["xbox"],
    location: { access: "on-wheel-tuning", path: "Tuning menu → ABS" },
    description:
      "Sets the intensity of the ABS vibration signal sent to the wheel (and connected pedal vibration motors if equipped). When the game signals ABS activation, you feel a pulsing through the wheel at this intensity.",
    valueType: { kind: "numeric", min: 0, max: 100, default: 50, unit: "%" },
    increaseEffect: "Stronger ABS pulse through the wheel — very clear haptic signal when brakes lock.",
    decreaseEffect: "Subtler ABS feedback — less intrusive, but harder to sense threshold braking.",
    sweetSpot: "40–70 is a reasonable starting range. High values can be distracting; find the level where ABS is noticeable but not jarring.",
    unverified: true,
  },
]
